FROM --platform=linux/amd64 rockylinux:9
RUN dnf install -y python3 python3-devel gcc make openssl-devel libffi-devel glibc-common glibc-devel findutils && dnf clean all
ENV PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
WORKDIR /build
COPY . .
RUN python3 -c 'import os, shutil; [os.remove(os.path.join(r, f)) for r, d, fs in os.walk(".") for f in fs if f == ".DS_Store" or f.endswith(".pyc")]; [shutil.rmtree(os.path.join(r, d)) for r, ds, f in os.walk(".") for d in ds if d == "__pycache__"]'
RUN python3 -m pip install --upgrade pip && python3 -m pip install pex==2.1.137 wheel setuptools
RUN python3 -m pip install --ignore-installed -r requirements.txt -r requirements_dev.txt
RUN PYTHONPATH=. pytest tellapart/aurproxytest/
RUN mkdir /build/src && cp -r /build/tellapart /build/src/ && cp -r /build/templates /build/src/
RUN pex -D /build/src -r requirements.txt -m tellapart.aurproxy.command -o aurproxy-9.pex --platform=manylinux_2_17_x86_64-cp-39-cp39
CMD ["cp", "aurproxy-9.pex", "/dist/"]
